# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-28 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='book_image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
