# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-07 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_list',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
