# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_list',
            options={'ordering': ['-date_created']},
        ),
    ]
