# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-10 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0002_book_list_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
