# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0002_auto_20180110_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_List',
            new_name='BookList',
        ),
    ]
