# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-15 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0004_auto_20180113_2154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_list',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='book_list',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
