# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-13 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0004_auto_20180113_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='book_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='book_list',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
