# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0005_auto_20180114_0058'),
        ('book_listing', '0005_auto_20180115_2058'),
    ]

    operations = [
    ]
