# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0006_merge_20180122_0056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_list',
            options={},
        ),
        migrations.RemoveField(
            model_name='book_list',
            name='date_created',
        ),
    ]
