# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0007_auto_20180122_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_list',
            name='author',
        ),
    ]
