# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 15:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0009_auto_20180125_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book_list',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='book_list',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 25, 15, 48, 2, 898319, tzinfo=utc)),
        ),
    ]
