# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0010_auto_20180125_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
