# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 15:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0011_auto_20180125_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_list',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
