# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_listing', '0012_auto_20180125_2120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_list',
            old_name='author',
            new_name='user',
        ),
    ]
