# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-03-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20190307_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-upvote_count']},
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
