# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-07 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_auto_20180106_1719'),
        ('forum', '0002_auto_20180105_1507'),
    ]

    operations = [
    ]
