# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 19:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0019_auto_20180121_1832'),
        ('forum', '0015_auto_20180114_0058'),
    ]

    operations = [
    ]
