# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-25 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0021_auto_20180122_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
