# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-21 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(upload_to='profile pics/'),
        ),
    ]
