# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-06 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0003_auto_20180306_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.FileField(default='/media/profile%20pics/default_user.png', upload_to='profile pics/'),
        ),
    ]
