# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-09 04:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_in', '0007_auto_20180309_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sap',
            field=models.BigIntegerField(unique=True),
        ),
    ]
